#Configuracoes do tomcat
server:
  shutdown: graceful
  servlet:
    context-path: /itau-supernova-frete
    encoding:
      charset: UTF-8
      enabled: true
  undertow:
    websocket:
      enabled: false
    threads:
      worker: 64 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # One IO thread per CPU core is a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2

supplier-properties:
  url: ${SUPPLIER_URL:http://localhost:8080/itau-supernova-supplier}
  read-timeout: ${SUPPLIER_READ_TIMEOUT:30000}
  connect-timeout: ${SUPPLIER_CONNECT_TIMEOUT:30000}
  x-application-key: ${SUPPLIER_X_APPLICATION_KEY:123}
  client-id: ${SUPPLIER_CLIENT_ID:123}
  client-secret: ${SUPPLIER_CLIENT_SECRET:123}
